/**
 * Seed data for RPG items
 */
export const itemsData = [
  // Weapons
  {
    name: "Dague rouillée",
    type: "weapon",
    price: 10,
    durability: 100,
    stats: { strength: 3, agility: 1 },
  },
  {
    name: "Épée courte",
    type: "weapon",
    price: 50,
    durability: 100,
    stats: { strength: 5, agility: 0 },
  },
  {
    name: "Hache de guerre",
    type: "weapon",
    price: 120,
    durability: 100,
    stats: { strength: 8, agility: -1 },
  },
  {
    name: "Arc long",
    type: "weapon",
    price: 80,
    durability: 100,
    stats: { agility: 4, strength: 3 },
  },
  {
    name: "Bâton de mage",
    type: "weapon",
    price: 65,
    durability: 100,
    stats: { magic: 6, strength: 1 },
  },
  {
    name: "Épée légendaire",
    type: "weapon",
    price: 500,
    durability: 150,
    stats: { strength: 12, agility: 3, luck: 2 },
  },
  {
    name: "Bâton de feu",
    type: "weapon",
    price: 350,
    durability: 90,
    stats: { magic: 10, strength: 2 },
  },
  {
    name: "Dagues jumelles",
    type: "weapon",
    price: 300,
    durability: 80,
    stats: { agility: 8, speed: 5, strength: 4 },
  },
  {
    name: "Marteau de guerre",
    type: "weapon",
    price: 200,
    durability: 120,
    stats: { strength: 10, speed: -2 },
  },
  {
    name: "Sceptre de puissance",
    type: "weapon",
    price: 450,
    durability: 100,
    stats: { magic: 12, charisma: 3 },
  },

  // Armor
  {
    name: "Armure de cuir",
    type: "armor",
    price: 45,
    durability: 80,
    stats: { agility: 2, strength: 1 },
  },
  {
    name: "Cotte de mailles",
    type: "armor",
    price: 120,
    durability: 120,
    stats: { strength: 3, agility: -1 },
  },
  {
    name: "Armure de plaques",
    type: "armor",
    price: 250,
    durability: 150,
    stats: { strength: 5, agility: -2, speed: -1 },
  },
  {
    name: "Robe de mage",
    type: "armor",
    price: 100,
    durability: 70,
    stats: { magic: 5, charisma: 2 },
  },
  {
    name: "Cape d'ombre",
    type: "armor",
    price: 180,
    durability: 60,
    stats: { agility: 4, speed: 3, luck: 2 },
  },
  {
    name: "Armure enchantée",
    type: "armor",
    price: 400,
    durability: 130,
    stats: { strength: 4, magic: 4, charisma: 2 },
  },
  {
    name: "Heaume de vaillance",
    type: "armor",
    price: 150,
    durability: 100,
    stats: { strength: 2, charisma: 3 },
  },
  {
    name: "Bouclier de dragon",
    type: "armor",
    price: 320,
    durability: 200,
    stats: { strength: 6, speed: -1 },
  },

  // Potions and consumables
  {
    name: "Potion de vie",
    type: "consumable",
    price: 25,
    durability: 100,
    stats: { health: 50 },
  },
  {
    name: "Élixir de mana",
    type: "consumable",
    price: 30,
    durability: 100,
    stats: { magic: 50 },
  },
  {
    name: "Potion de force",
    type: "consumable",
    price: 40,
    durability: 100,
    stats: { strength: 5, duration: 3 },
  },
  {
    name: "Potion d'agilité",
    type: "consumable",
    price: 40,
    durability: 100,
    stats: { agility: 5, duration: 3 },
  },
  {
    name: "Antidote",
    type: "consumable",
    price: 15,
    durability: 100,
    stats: { curePoison: true },
  },
  {
    name: "Pain elfique",
    type: "consumable",
    price: 10,
    durability: 100,
    stats: { health: 20 },
  },
  {
    name: "Potion de chance",
    type: "consumable",
    price: 60,
    durability: 100,
    stats: { luck: 5, duration: 5 },
  },

  // Miscellaneous items
  {
    name: "Amulette du pouvoir",
    type: "accessory",
    price: 200,
    durability: 100,
    stats: { magic: 3, charisma: 2 },
  },
  {
    name: "Anneau de vie",
    type: "accessory",
    price: 150,
    durability: 100,
    stats: { health: 15 },
  },
  {
    name: "Bottes rapides",
    type: "accessory",
    price: 120,
    durability: 90,
    stats: { speed: 5, agility: 2 },
  },
  {
    name: "Gants de force",
    type: "accessory",
    price: 100,
    durability: 80,
    stats: { strength: 3 },
  },
  {
    name: "Porte-bonheur",
    type: "accessory",
    price: 80,
    durability: 100,
    stats: { luck: 4 },
  },
];
